version: "3"

services:
  demo:
    container_name: boot-demo
    image: docker-demo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8090:8090"
    restart: always
    volumes:
    - demo-data:/tmp
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
volumes:
  demo-data:
    driver: local